### PR TITLE
Use hardware serial port on Teensy boards

### PR DESCRIPTION
**Pull request by PaulStoffregen**
All Teensy boards have Serial1 which is not shared with USB.

... and thanks for the kind words about AltSoftSerial... (I'm the author)

### CODE REVIEW

**Comment by SlashDevin** [comment]
Thanks, I was just researching the ports on the Teensy.

**Comment by PaulStoffregen** [comment]
Do you have any Teensy boards for testing?  Want some??

**Comment by SlashDevin** [comment]
> Do you have any Teensy boards for testing? Want some??

A generous and tempting offer!  Thanks, but I really can't right now.

BTW, I just discovered that there is a preprocessor symbol for choosing an "extra" serial port: `SERIAL_PORT_HARDWARE_OPEN`.  It's defined in the variants.h files.    The comments even mention using it to connect a GPS device.  Now they tell me!  &nbsp;&nbsp;&nbsp;:)

I also noticed that your `pgm_read_ptr` fix has percolated through to the other platforms.  Woot.

**Comment by PaulStoffregen** [comment]
Ok.  If you change your mind and want to play with a board having 6 real hardware serial ports, just say the word....

**Pull request merged**
